# run the pipeline on changes in main branch
trigger:
  - main
# build environment - OS
pool:
  vmImage: 'ubuntu-latest'
steps:
  # build environment - Node
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'install node.js'
  # NPM task
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'
  # Git task
  - script: |
      # remove git history and settings - to avoid inheritance
      rm -rf .git
      # re-initialise git
      git init
      git config user.name "jpark189"
      git config user.email "joungbihn_park@brown.edu"
      git remote set-url origin https://joungbihn:${GIT_TOKEN}@github.com/joungbihn/portfolio.git
      # add and commit /docs/ folder
      git add docs
      git commit -m "deploy the bundle"
      # push the commit to the public repository
      git push origin HEAD:main --force
    displayName: 'deploy the production bundle'